### ISSUE TITLE
Could be cool to curl your uncenter.dev

### ISSUE THREAD

**Issue by pi0** [uncenter/uncenter.dev#78]
Nice bio design. I was tempted to directly `curl uncenter.dev` if I see the JSON output only haha. (you might use user agent check like [this](https://github.com/unjs/nitro/blob/7a2802749fa62bfeacfe67a21593cb9549a5c860/src/runtime/utils.ts#L42))

**Comment by uncenter** [comment]
I love this idea! It should be working now, try `curl "https://uncenter.dev/"` (or even better, `curl "https://uncenter.dev/" | bat --language json`).
