### ISSUE TITLE
Small Typo in Fortran Post

### ISSUE THREAD

**Issue by andy-bond** [uncenter/uncenter.dev#92]
Hey @uncenter - I was reading your Fortran post and wanted to just let you know you left a tiny punctuation mark off in one of the first paragraphs.

On this line: https://github.com/uncenter/uncenter.dev/blob/main/src/posts/learning-fortran.md?plain=1#L17
You are missing a period before "The free form layout" :)

---

Also thanks for the `eleventy-plugin-icons` - I just found it today & migrated to it!

**Comment by uncenter** [comment]
Thanks for letting me know! Also glad to here that you are enjoying the plugin :)
